"""
Output handler for saving summaries in various formats.
"""
import os
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional


class OutputManager:
    """Handles saving summaries in multiple formats with organized folder structure."""

    def __init__(self, base_dir: str = '.', folder_structure: str = 'by_date', show_name: str = None):
        """
        Initialize output handler.

        Args:
            base_dir: Base directory for outputs
            folder_structure: 'flat', 'by_date', or 'by_show'
            show_name: Show name for organization (e.g., 'bloomberg_brief')
        """
        self.base_dir = Path(base_dir)
        self.folder_structure = folder_structure
        self.show_name = show_name

    def _get_output_dir(self, date: datetime, output_type: str) -> Path:
        """
        Get output directory based on folder structure setting.

        Args:
            date: Date for the summary
            output_type: 'summaries' or 'transcripts'

        Returns:
            Path to output directory
        """
        if self.folder_structure == 'by_show' and self.show_name:
            # Structure: summaries/bloomberg_brief/2026-01-14/
            date_str = date.strftime('%Y-%m-%d')
            output_dir = self.base_dir / output_type / self.show_name / date_str
        elif self.folder_structure == 'by_date':
            # Structure: summaries/2026-01-13/
            date_str = date.strftime('%Y-%m-%d')
            output_dir = self.base_dir / output_type / date_str
        else:
            # Flat structure: summaries/
            output_dir = self.base_dir / output_type

        output_dir.mkdir(parents=True, exist_ok=True)
        return output_dir

    def save_summary_markdown(
        self,
        summary_text: str,
        video_metadata: Dict,
        summary_metadata: Dict,
        date: Optional[datetime] = None
    ) -> str:
        """
        Save summary as markdown file.

        Args:
            summary_text: The summary content (already in markdown)
            video_metadata: Video information
            summary_metadata: Summary metadata (tokens, model, etc.)
            date: Date for folder organization (defaults to now)

        Returns:
            Path to saved file
        """
        if date is None:
            date = datetime.now()

        output_dir = self._get_output_dir(date, 'summaries')
        video_id = video_metadata.get('video_id', 'unknown')
        timestamp = date.strftime('%Y%m%d_%H%M%S')

        filename = output_dir / f"summary_{video_id}_{timestamp}.md"

        # Build markdown content with metadata header
        content = f"""# {video_metadata.get('title', 'Video Summary')}

**Channel:** {video_metadata.get('channel_title', 'Unknown')}
**Published:** {video_metadata.get('published_at', 'Unknown')}
**Video URL:** {video_metadata.get('url', 'N/A')}
**Summary Generated:** {date.strftime('%Y-%m-%d %H:%M:%S')}

---

{summary_text}

---

*Generated by The Great Information Gatherer*
*Model: {summary_metadata.get('model', 'N/A')} | Tokens: {summary_metadata.get('tokens_used', {}).get('input', 0)} input, {summary_metadata.get('tokens_used', {}).get('output', 0)} output*
"""

        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"Summary saved to {filename}")
        return str(filename)

    def save_summary(
        self,
        summary_data: Dict,
        markdown_content: str,
        date: Optional[datetime] = None
    ) -> Dict[str, str]:
        """
        Save summary in both JSON and markdown formats.

        Args:
            summary_data: Complete summary data dictionary
            markdown_content: Markdown formatted summary
            date: Date for folder organization (defaults to now)

        Returns:
            Dictionary with paths to saved files
        """
        saved_files = {}

        # Save JSON
        json_path = self.save_summary_json(summary_data, date)
        saved_files['json'] = json_path

        # Save Markdown
        md_path = self.save_summary_markdown(
            markdown_content,
            summary_data.get('video_metadata', {}),
            summary_data,
            date
        )
        saved_files['markdown'] = md_path

        return saved_files

    def save_summary_json(
        self,
        summary_data: Dict,
        date: Optional[datetime] = None
    ) -> str:
        """
        Save summary as JSON file.

        Args:
            summary_data: Complete summary data dictionary
            date: Date for folder organization (defaults to now)

        Returns:
            Path to saved file
        """
        if date is None:
            date = datetime.now()

        output_dir = self._get_output_dir(date, 'summaries')
        video_id = summary_data.get('video_metadata', {}).get('video_id', 'unknown')
        timestamp = date.strftime('%Y%m%d_%H%M%S')

        filename = output_dir / f"summary_{video_id}_{timestamp}.json"

        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(summary_data, f, indent=2, ensure_ascii=False)

        print(f"Summary JSON saved to {filename}")
        return str(filename)

    def save_transcript(
        self,
        transcript_data: Dict,
        date: Optional[datetime] = None
    ) -> str:
        """
        Save transcript as JSON file.

        Args:
            transcript_data: Transcript data dictionary
            date: Date for folder organization (defaults to now)

        Returns:
            Path to saved file
        """
        if date is None:
            date = datetime.now()

        output_dir = self._get_output_dir(date, 'transcripts')
        video_id = transcript_data['video_id']
        timestamp = date.strftime('%Y%m%d_%H%M%S')

        filename = output_dir / f"transcript_{video_id}_{timestamp}.json"

        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(transcript_data, f, indent=2, ensure_ascii=False)

        print(f"Transcript saved to {filename}")
        return str(filename)

    def get_latest_summary_path(self, output_type: str = 'markdown') -> Optional[str]:
        """
        Get path to most recent summary file.

        Args:
            output_type: 'markdown' or 'json'

        Returns:
            Path to latest summary or None
        """
        summaries_dir = self.base_dir / 'summaries'
        if not summaries_dir.exists():
            return None

        extension = '.md' if output_type == 'markdown' else '.json'

        # Search all subdirectories if using date structure
        if self.folder_structure == 'by_date':
            all_files = list(summaries_dir.glob(f'**/*{extension}'))
        else:
            all_files = list(summaries_dir.glob(f'*{extension}'))

        if not all_files:
            return None

        # Get most recent by modification time
        latest = max(all_files, key=lambda p: p.stat().st_mtime)
        return str(latest)
